-- MySQL Script generated by MySQL Workbench
-- 06/07/18 16:38:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalho_2_bimestre_serv_inter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho_2_bimestre_serv_inter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `trabalho_2_bimestre_serv_inter` ;

-- -----------------------------------------------------
-- Table `trabalho_2_bimestre_serv_inter`.`atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_2_bimestre_serv_inter`.`atleta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `idade` INT NULL,
  `numero_camiseta` INT NULL,
  `posicao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
